// Nivel 5/livro-servidor/clientes/livros-angular/src/app/LivroDados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../Livro';
import { Editora } from '../Editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    //this.livro = new Livro(null,0,'','',[]);
    this.livro = new Livro();
  }

  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras;
    });
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluirLivro(this.livro).then((sucesso) => {
      if (sucesso) {
        console.log('Livro incluído com sucesso!');
        this.router.navigateByUrl('/lista');
      } else {
        console.log('Erro ao incluir o livro');
      }
    });
  };
}

<main class="d-flex flex-column h-100 w-100 px-5">
    <h1>Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <label for="titulo">Título:</label>
        <input class="form-control" id="titulo" type="text" required [(ngModel)]="livro.titulo" name="titulo">

        <label for="resumo" class="form-label w-100">Resumo:</label>
        <textarea id="resumo" required [(ngModel)]="livro.resumo" name="resumo" class="form-control"></textarea>

        <label for="editora" class="form-label w-100">Editora:</label>
        
        <select id="editora" name="editora" class="form-control" [(ngModel)]="livro.codEditora">
            <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>

        <label for="autores" class="form-label w-100">Autores (1 por linha)</label>
        <textarea id="autores" required [(ngModel)]="autoresForm" name="autores" class="form-control"></textarea>

        <button type="submit" class="btn btn-primary mt-3">Salvar Dados</button>
    </form>
</main>

// Nivel 5/livro-servidor/clientes/livros-react/src/componentes/LivroDados.js
import React, { useState, useEffect, useMemo } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import ControleLivro from "../controle/ControleLivros";
import ControleEditora from "../controle/ControleEditora";
import { useNavigate } from "react-router-dom";

function LivroDados() {
  const controleLivro = useMemo(() => new ControleLivro(), []);
  const controleEditora = useMemo(() => new ControleEditora(), []);

  const [opcoes, setOpcoes] = useState([]);
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(
    opcoes.length > 0 ? opcoes[0].value : 1 
  );

  const navigate = useNavigate();

  useEffect(() => {
    const editoras = controleEditora.getEditoras();
    const opcoes = editoras.map((editora) => ({
      value: editora.codEditora,
      text: editora.nome,
    }));
    setOpcoes(opcoes);
  }, [controleEditora]);

  function tratarCombo(event) {
    const valorSelecionado = Number(event.target.value);
    setCodEditora(valorSelecionado);
  }

  async function incluir(event) {
    event.preventDefault();

    // Construtor do livro
    const novoLivro = {
      codigo: null,
      titulo: titulo,
      resumo: resumo,
      codEditora: codEditora,
      autores: autores.split("\n"),
    };

    try {
      await controleLivro.incluirLivro(novoLivro);
      navigate("/");
    } catch (error) {
      console.error("Erro ao incluir livro:", error);
    }
  }


  return (
    <main className="d-flex flex-column h-100 w-100 px-5">
      <h1>Dados do Livro</h1>
      <label htmlFor="titulo" className="form-label w-100">
        Título:
      </label>

      <input
        id="titulo"
        type="text"
        value={titulo}
        onChange={(e) => setTitulo(e.target.value)}
        className="form-control"
      />
      <label htmlFor="resumo" className="form-label w-100">
        Resumo:
      </label>

      <textarea
        id="resumo"
        type="text"
        value={resumo}
        onChange={(e) => setResumo(e.target.value)}
        className="form-control"
      />
      {/* combobox */}
      <label htmlFor="editora" className="form-label w-100">
        Editora:
      </label>
      <select className="form-control" id="editora" onChange={tratarCombo}>
        {opcoes.map((opcao) => (
          <option key={opcao.value} value={opcao.value}>
            {opcao.text}
          </option>
        ))}
      </select>

      <label htmlFor="autores" className="form-label w-100">
        Autores(1 por linha):
      </label>
      <textarea
        id="autores"
        type="text"
        value={autores}
        onChange={(e) => setAutores(e.target.value)}
        className="form-control"
      />
      <form onSubmit={incluir}>
        <button className="btn btn-primary mt-3" type="submit">
          Salvar Dados
        </button>
      </form>
    </main>
  );
}

export default LivroDados;
