// Nivel 5/livro-servidor/clientes/livros-angular/src/app/LivroDados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../Livro';
import { Editora } from '../Editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    //this.livro = new Livro(null,0,'','',[]);
    this.livro = new Livro();
  }

  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras;
    });
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluirLivro(this.livro).then((sucesso) => {
      if (sucesso) {
        console.log('Livro incluído com sucesso!');
        this.router.navigateByUrl('/lista');
      } else {
        console.log('Erro ao incluir o livro');
      }
    });
  };
}

<main class="d-flex flex-column h-100 w-100 px-5">
    <h1>Dados do Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <label for="titulo">Título:</label>
        <input class="form-control" id="titulo" type="text" required [(ngModel)]="livro.titulo" name="titulo">

        <label for="resumo" class="form-label w-100">Resumo:</label>
        <textarea id="resumo" required [(ngModel)]="livro.resumo" name="resumo" class="form-control"></textarea>

        <label for="editora" class="form-label w-100">Editora:</label>
        
        <select id="editora" name="editora" class="form-control" [(ngModel)]="livro.codEditora">
            <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>

        <label for="autores" class="form-label w-100">Autores (1 por linha)</label>
        <textarea id="autores" required [(ngModel)]="autoresForm" name="autores" class="form-control"></textarea>

        <button type="submit" class="btn btn-primary mt-3">Salvar Dados</button>
    </form>
</main>

// Nivel 5/livro-servidor/clientes/livros-next/src/pages/LivroDados.tsx
import React, { useState, useEffect, ChangeEvent, FormEvent } from "react";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Menu } from "@/classes/componentes/Menu";
import ControleEditora, { arrayEditoras } from "@/classes/controle/ControleEditora";
import  ControleLivros  from "@/classes/controle/ControleLivros";
import { Livro } from "@/classes/modelo/Livro";

interface Opcao {
  value: number;
  text: string;
}
const LivroDados: NextPage = () => {
  const [opcoes, setOpcoes] = useState<Opcao[]>([]);
  const [controleLivros] = useState(new ControleLivros([]));

  useEffect(() => {
    const controleEditora = new ControleEditora(arrayEditoras);
    const editoras = controleEditora.getEditoras();
    const opcoes = editoras.map((editora) => ({
      value: editora.codEditora,
      text: editora.nome,
    }));
    setOpcoes(opcoes);
  }, []);

  const router = useRouter();
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState( //para trazer a editora correta value 1
    opcoes.length > 0 ? opcoes[0].value : 1 
  );

  const tratarCombo = (event: ChangeEvent<HTMLSelectElement>) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const novoLivro = new Livro(
      null, 
      Number(codEditora),
      titulo,
      resumo,
      autores.split("\n")
    );
    try {
      controleLivros.incluirLivro(novoLivro);
      router.push("/LivroLista");
    } catch (error) {
      console.error("Erro ao incluir livro:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>LivroDados</title>
        <meta name="description" content="Inclusão de Livros" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="d-flex flex-column h-100 w-100 px-5">
        <h1>Novo Livro</h1>
        <form onSubmit={incluir}>
          <div>
            <label htmlFor="titulo" className="form-label w-100">Título:</label>
            <input
              id="titulo"
              type="text"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
              className="form-control"
            />
          </div>
          <div>
            <label htmlFor="resumo" className="form-label w-100">Resumo:</label>
            <textarea
              id="resumo"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
              className="form-control"
            />
          </div>
          <div>
            <label htmlFor="editora" className="form-label w-100">Editora:</label>
            <select className="form-control" id="editora" value={codEditora} onChange={tratarCombo}>
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label htmlFor="autores" className="form-label w-100">Autores:</label>
            <textarea
              id="autores"
              value={autores}
              onChange={(e) => setAutores(e.target.value)}
              className="form-control"
            />
          </div>

          <button type="submit" className="btn btn-primary mt-3">Salvar Dados</button>
        </form>
      </main>
    </div>
  );
};
export default LivroDados;
