// Nivel 5/livro-servidor/clientes/livros-react/src/componentes/LivroLista.js
import React, { useState, useEffect, useMemo } from "react";
import Table from "react-bootstrap/Table";
import ControleLivro from "../controle/ControleLivros";
import ControleEditora from "../controle/ControleEditora";
import "bootstrap/dist/css/bootstrap.min.css";

function LinhaLivro({ livro, excluir }) {
  const handleDelete = () => {
    excluir(livro.codigo);
  };
  return (
    <tr>
      <td>
        {livro.titulo}
        <br />
        <button className="btn btn-danger" onClick={handleDelete}>
          {" "}
          Excluir{" "}
        </button>
      </td>
      <td className="resumo-coluna">{livro.resumo}</td>
      <td>{livro.nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={`${livro.codigo}-${index}`}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  const controleLivro = useMemo(() => new ControleLivro(), []);
  const controleEditora = useMemo(() => new ControleEditora(), []);

  useEffect(() => {
    if (!carregado) {
      controleLivro.obterLivros().then((dadosLivros) => {
        const livrosComNomeEditora = dadosLivros.map((livro) => {
          const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
          return { ...livro, nomeEditora };
        });

        setLivros(livrosComNomeEditora);
        setCarregado(true);
      });
    }
  }, [carregado, controleLivro, controleEditora]);

  const excluir = (codigo) => {
    controleLivro.excluirLivro(codigo).then(() => {
      setCarregado(false);
    });
  };

  return (
    <main className="d-flex flex-column h-100 w-100 px-5">
      <h1>Catálogo de Livros</h1>
      {carregado ? (
        <Table striped bordered hover>
          <thead>
            <tr>
              <th className="bg-dark text-white">Título</th>
              <th className="bg-dark text-white">Resumo</th>
              <th className="bg-dark text-white">Editora</th>
              <th className="bg-dark text-white">Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro key={`${livro.codigo}-${index}`} livro={livro} excluir={excluir} />
            ))}
          </tbody>
        </Table>
      ) : (
        <p>Carregando...</p>
      )}
    </main>
  );
}

// Nivel 5/livro-servidor/clientes/livros-angular/src/app/LivroLista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../Editora';
import { Livro } from '../Livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }
  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe((editoras) => {
      this.editoras = editoras;
    });

    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir = async (codigo:string | null): Promise<void> => {
    try {
      await this.servLivros.excluirLivro(codigo);
      this.livros = await this.servLivros.obterLivros();
    } catch (error) {
      console.error('Erro ao excluir o livro:', error);
    }
  };
  
  obterNome = (codEditora: number): string | undefined => {
    const editora = this.editoras.find((e) => e.codEditora == codEditora);
    if (!editora) {
      console.log('Editora não encontrada:', codEditora);
    }

    return editora ? editora.nome : undefined;
  };
}
//erro ao incluir novo livro com a editora na tabela, e.codEditora == codEditora, para converter 
// ambos os lados para que encontrasse corretamente, ('5'== 5 = true) e com erro('5'=== 5 = false)


<main class="d-flex flex-column h-100 w-100 px-5">
    <h1 class="my-4">Lista de Livros</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th class="bg-dark text-white ">Título</th>
                <th class="bg-dark text-white ">Resumo</th>
                <th class="bg-dark text-white ">Editora</th>
                <th class="bg-dark text-white ">Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br>
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>
                    {{ obterNome(livro.codEditora) }}
                </td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>
